In [1]:
import pandas as pd

In [2]:
play_df=pd.read_csv('NFL Play by Play 2009-2016 (v3).csv')

C:\Users\Lenovo\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (25,51) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
play_df.head()

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,NaN,15:00,15,3600.0,0.0,TEN,...,NaN,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,NaN,NaN,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,NaN,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,NaN,NaN,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,NaN,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,NaN,NaN,2009

In [5]:
play_df.isnull().sum()[0:15]

Date                0
GameID              0
Drive               0
qtr                 0
down            54218
time              188
TimeUnder           0
TimeSecs          188
PlayTimeDiff      374
SideofField       450
yrdln             723
yrdline100        723
ydstogo             0
ydsnet              0
GoalToGo          723
dtype: int64

In [6]:
play_df2=play_df.copy()

In [7]:
play_df2.dropna(axis=1,inplace=True)

In [8]:
print(play_df.shape)
print(play_df2.shape)

(362447, 102)
(362447, 41)

In [9]:
play_df3=play_df.copy()

In [10]:
play_df3.fillna(0)

,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,...,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season
0,2009-09-10,2009091000,1,1,0.0,15:00,15,3600.0,0.0,TEN,...,0.000000,0.485675,0.514325,0.546433,0.453567,0.485675,0.060758,0.000000,0.000000,2009
1,2009-09-10,2009091000,1,1,1.0,14:53,15,3593.0,7.0,PIT,...,1.146076,0.546433,0.453567,0.551088,0.448912,0.546433,0.004655,-0.032244,0.036899,2009
2,2009-09-10,2009091000,1,1,2.0,14:16,15,3556.0,37.0,PIT,...,0.000000,0.551088,0.448912,0.510793,0.489207,0.551088,-0.040295,0.000000,0.000000,2009
3,2009-09-10,2009091000,1,1,3.0,13:35,14,3515.0,41.0,PIT,...,-5.031425,0.510793,0.489207,0.461217,0.538783,0.510793,-0.049576,0.106663,-0.156239,2009
4,2009-09-10,2009091000,1,1,4.0,13:27,14,3507.0,8.0,PIT,...,0.000000,0.461217,0.538783,0.558929,0.441071,0.461217,0.097712,0.000000,0.000000,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362442,2017-01-01,2017010102,20,4,1.0,00:22,1,22.0,6.0,GB,...,0.000000,0.051901,0.948099,0.093435,0.906565,0.051901,0.041534,0.041534,0.000000,2016
362443,2017-01-01,2017010102,20,4,0.0,00:13,1,13.0,9.0,GB,...,0.000000,0.093435,0.906565,0.034069,0.965931,0.093435,-0.059366,0.000000,0.000000,2016
362444,2017-01-01,2017010102,21,4,0.0,00:13,1,13.0,0.0,DET,...,0.000000,0.034069,0.965931,0.035708,0.964292,0.965931,-0.001639,0.000000,0.000000,2016
362445,2017-01-01,2017010102,21,4,1.0,00:12,1,12.0,1.0,DET,...,0.000000,0.035708,0.964292,0.000000,1.000000,0.964292,0.035708,0.000000,0.000000,2016
362446,2017-01-01,2017010102,21,4,0.0,00:00,0,0.0,12.0,DET,...,0.000000,0.000000,1.000000,0.000000,1.000000,0.934245,0.000000,0.000000,0.000000,2016

In [12]:
play_df.Date.dtypes

dtype('O')

In [13]:
play_df.columns

Index(['Date', 'GameID', 'Drive', 'qtr', 'down', 'time', 'TimeUnder',
       'TimeSecs', 'PlayTimeDiff', 'SideofField',
       ...
       'yacEPA', 'Home_WP_pre', 'Away_WP_pre', 'Home_WP_post', 'Away_WP_post',
       'Win_Prob', 'WPA', 'airWPA', 'yacWPA', 'Season'],
      dtype='object', length=102)

In [15]:
play_df.columns=play_df.columns.str.lower()

In [16]:
play_df.columns

Index(['date', 'gameid', 'drive', 'qtr', 'down', 'time', 'timeunder',
       'timesecs', 'playtimediff', 'sideoffield',
       ...
       'yacepa', 'home_wp_pre', 'away_wp_pre', 'home_wp_post', 'away_wp_post',
       'win_prob', 'wpa', 'airwpa', 'yacwpa', 'season'],
      dtype='object', length=102)

In [20]:
play_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
362442    False
362443    False
362444    False
362445    False
362446    False
Length: 362447, dtype: bool